schema_version = "1"

[[strategy]]
id = "capture_alignment_profile"
enabled = true

[[strategy]]
id = "input_timing_variant"
enabled = true

[[strategy]]
id = "service_stub_profile_switch"
enabled = true

[[strategy]]
id = "patch_set_variant"
enabled = true

[[strategy]]
id = "lift_mode_variant"
enabled = true

[[strategy]]
id = "runtime_mode_variant"
enabled = true
