[package]
name = "recomp-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
recomp-gfx = { path = "../recomp-gfx" }
recomp-services = { path = "../recomp-services" }
recomp-timing = { path = "../recomp-timing" }
thiserror = "1.0"
